version: 0.2

phases:
  build:
    commands:
      - apt-get update
      - apt-get install -y zip unzip
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build Finished on `date`
      - zip -qr aws-cicd.zip ./*
      - ls
      - aws lambda update-function-code --function-name aws-cicd-fe --zip-file fileb://aws-cicd.zip