# version: 0.2
# phases:
#   install:
#     commands:
#       - apt-get update
#       - apt-get install -y zip unzip
#   build:
#     commands:
#       - echo Build started on `date`
#   post_build:
#     commands:
#       - echo Build Finished on `date`
#       - zip -qr aws-cicd.zip ./*
#       - ls
#       - aws lambda update-function-code --function-name aws-cicd-fe --zip-file fileb://aws-cicd.zip

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Running pre-build commands..."
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build finished on `date`
      - zip -qr aws-cicd.zip ./*
      - aws lambda update-function-code --function-name aws-cicd-fe --zip-file fileb://aws-cicd.zip || true